# Generated by Django 2.1.5 on 2019-02-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
