# Generated by Django 2.1.5 on 2019-02-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20190220_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
