# Generated by Django 2.1.5 on 2019-02-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_auto_20190220_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='phone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
