# Generated by Django 2.2.3 on 2019-11-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20191127_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
