# Generated by Django 2.2.3 on 2019-11-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20191128_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='publication',
        ),
        migrations.AddField(
            model_name='publication',
            name='answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Answer'),
        ),
    ]
