# Generated by Django 2.2.3 on 2019-11-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20191128_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.Publication'),
            preserve_default=False,
        ),
    ]
