# Generated by Django 2.2.3 on 2019-12-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20191205_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipPubAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ManyToManyField(related_name='answer', to='forum.Answer')),
                ('publication', models.ManyToManyField(related_name='publication', to='forum.Publication')),
            ],
        ),
    ]
