# Generated by Django 2.1.5 on 2019-02-25 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('complement', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=9)),
                ('price', models.CharField(max_length=8)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='media/%Y/%m/%d/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on: ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update on: ')),
                ('slug', models.SlugField(max_length=100, verbose_name='Unique identifier')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['title'],
            },
        ),
    ]
