# Generated by Django 2.1.5 on 2019-02-25 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='slug',
        ),
    ]
