# Generated by Django 2.1.5 on 2019-02-22 01:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('banner', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem')),
            ],
        ),
    ]
