# Generated by Django 2.2.3 on 2019-07-22 17:57

import cloudinary.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('banner', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem')),
            ],
        ),
    ]
